### ISSUE TITLE
Tag commits with version numbers.

### ISSUE THREAD

**Issue by conny-nyman** [purplespider/silverstripe-file-listing#13]
This repository have different branches available (`3.0`, `3.1`, `4.0` and `master`) but no tags. 

Currently you need to require `dev-master` in composer in order to get the latest version _(as the 4.0 branch is behind master.)_, and right now the code on `master` is compatible with SS 4, but if this module would start supporting SS 5 in the future with breaking changes, then running a `composer update` command would make composer throw errors. _(If running composer update in a SS 4 project)_

Adding tags makes it safe to run `composer update` in any project without worrying about incompatible versions _(as long as semantic versioning is followed ofc.)_.

**Comment by purplespider** [comment]
I've added tags, would you mind checking I've done so correctly and am adhering to best practice? Thanks!

**Comment by conny-nyman** [comment]
The tags are correct and they currently follow the semantic versioning conventions/rules. 
If this project supports semantic versioning, it could be good to mention it in the readme somewhere.

As the tags are fixed now I will close the issue. Thanks! :+1:
