### ISSUE TITLE
FilePage not being seen during dev/build - no _config.php

### ISSUE THREAD

**Issue by Makreig** [purplespider/silverstripe-file-listing#9]
because there's no _config.php silverstripe isn't seeing this module and so isn't adding the FilePage class.

**Comment by mlewis-everley** [comment]
As far as I understand it, Silverstripe requires an _config.php file (even if empty) in order to recognise a folder as a module?

**Comment by purplespider** [comment]
Apologies, it did have an empty _config dir which fulfilled this purpose, but obviously empty directories don't get added to the repo! Should now be resolved.
